### ISSUE TITLE
Blank page on pocketcampaigns/adventurers/username

### ISSUE THREAD

**Issue by dhartjes** [HerbGlitch/pocketcampaigns#17]
Steps:
1. Login
2. Redirect to pocketcampaigns/adventurers/username
3. Screen is blank.

Tried:
Ctrl+F5
Opening dev tools, disabling cache, and refreshing
New user account

In the dev tools, I'm seeing a 404 error on the get attempt for https://pocketcampaigns.org/static/home/img/favicon.ico.

Thanks!
Dominic

**Comment by HerbGlitch** [comment]
Thank you for opening this issue.

This issue is due to the creation of the module 'Adventurer' and it was addded after users were created. I am still trying to figure out when is the best time to link these objects because they are linked via pk. Another cause for this is token creation. It should be created on register, but I might have placed it in the wrong area. For the current time, I will manually add users tokens. I hope this clears things up. I will add you right now.

**Comment by HerbGlitch** [comment]
Sooo, as it turns out, the model for token and adventurer were created successfully, but I believe that adventurer does not save properly so I have to "save" in the admin panel to fix the problem. I just tried to fix your account, please let me know if it works.

**Comment by HerbGlitch** [comment]
In regards to the .ico error, I believe that I have to path to the file on the server. I remember an option for it in nginx, but didn't think about it till now. I will prioritize that second as it should not break the site in any way

**Comment by dhartjes** [comment]
Yeah, it looks like my primary account is able to get in now. Thanks!
